### ISSUE TITLE
metrics not published on /metrics url

### ISSUE THREAD

**Issue by bizzyman7** [prometheus/graphite_exporter#229]
Hi, Just a help wanted issue I believe.

I'm attempting to convert over to prometheus from graphite and starting small.

I'm sending metric:
```
echo "stats.test.Testing123.10.10.12.26.avg.server1.System.Processes.mysqld.cpu 15.0 1682733244" | nc -q "0" 10.113.54.90 9109
```
With debug on, I see a message like this from the exporter:

```
ts=2023-04-29T04:55:06.943Z caller=collector.go:183 level=debug msg="Processing sample" sample="collector.graphiteSample{OriginalName:\"stats.test.Testing123.10.10.12.26.avg.server1.System.Processes.mysqld.cpu\", Name:\"fmc_prcocess_cpu_pct\", Labels:prometheus.Labels{\"job\":\"Testing123\", \"process\":\"mysqld\"}, Help:\"Graphite metric fmc_prcocess_cpu_pct\", Value:12.0, Type:2, Timestamp:time.Date(2023, time.April, 29, 4, 34, 45, 0, time.Local)}"
```

Config:
```
- match: stats.*.*.*.*.*.*.avg.server1.System.*.*.cpu
  name: fmc_prcocess_cpu_pct
  labels:
    job: $2
    process: $8
```

However I never this metric on http://localhost:9108/metrics

Am I doing something wrong?
