### ISSUE TITLE
getool: whisper import mapping not working?

### ISSUE THREAD

**Issue by robvalca** [prometheus/graphite_exporter#249]
Hi,
I'm using graphite_exporter `0.15.0` successfully with the following simple mapping file:

```
mappings:
- match: cback.*.summary.*.*
  name: cback_summary_$3
  labels:
    group: $1
    role: $2
- match: cback.*.*.*.*
  name: cback_job_$4
  labels:
    group: $1
    role: $2
    hostname: $3
```
I'm testing to import some old Whisper data (generated by the same producer that is now sending to `graphite_exporter`). I'm trying to use `getool create-blocks` but pointing to the same mapping file seems that is not doing the thing (i use `--graphite.mapping-strict-match`)  and nothing gets converted. If I remove the strict mapping, it converts the metrics in a direct translation mode (no labels). 

Can I get some advice about how to configure the mapping file for the whisper import (I would expect the same file to work, but it seems that is not the case)

Thanks in advance,
