### ISSUE TITLE
advice for mapping rule

### ISSUE THREAD

**Issue by zenglian** [prometheus/graphite_exporter#60]
I think this is tricky (7 lines):

```
- match:  '*.*.jvm.*.*'
  name: 'jvm_memory_usage'
  labels:
    application: $1
    executor_id: $2
    mem_type: $3
    qty: $4
```
And this is simpler (2 lines) and more intuitive. In below case `{}` can be omitted:

```
-   name: 'jvm_memory_usage'
    match: '${application}.${executor_id}.jvm.${mem_type}.${qty}'
```
